[project]
name = "lab3_penguins"
version = "0.1.0"
description = "Penguin species predictor using XGBoost and FastAPI"
dependencies = [
    "fastapi",
    "uvicorn",
    "xgboost",
    "pandas",
    "scikit-learn",
    "seaborn"
]
